name: Validate

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: '🧪 Test'
    runs-on: ubuntu-latest

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: '⚙️ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true

      - name: '⛓️ Install dependencies'
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: '✅ Test files'
        uses: ./
        with:
          name: artifact
          path: |
            README.md
            LICENSE
          retention-days: 1

      - name: '✅ Test files do not exist'
        uses: ./
        with:
          name: 'no_artifact'
          path: |
            dist/
            packages/**/dist/
          retention-days: 1

      - name: '🧹 Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1
